package com.campkin.service;
import com.campkin.api.ApiModels.GroupRequest; import com.campkin.domain.*; import com.campkin.repo.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import java.util.stream.*;
@Service @RequiredArgsConstructor public class AssignmentService {
 private final CampRepository camps; private final CamperRepository campers; private final RoomRepository rooms; private final DiscussionGroupRepository groups; private final PreferenceRepository preferences;
 @Transactional public void assignRooms(UUID campId){var camp=camps.findById(campId).orElseThrow();List<Camper> all=campers.findByCampIdOrderByName(campId);List<Room> rs=rooms.findByCampIdOrderByName(campId);for(Camper c:all)c.setRoom(null);for(Domain.Gender gender:Domain.Gender.values()){List<Camper> people=all.stream().filter(c->c.getGender()==gender).toList();List<Room> available=rs.stream().filter(r->r.getGender()==gender).toList();int beds=available.stream().mapToInt(Room::getCapacity).sum();if(beds<people.size())throw new IllegalStateException("Not enough "+gender.name().toLowerCase()+" room capacity: need "+people.size()+", have "+beds);Map<UUID,Set<UUID>>friends=friendMap(campId);List<List<Camper>>components=components(people,friends);components.sort(Comparator.<List<Camper>>comparingInt(List::size).reversed().thenComparing(x->x.getFirst().getName()));Map<UUID,List<Camper>>placed=available.stream().collect(Collectors.toMap(Room::getId,x->new ArrayList<>(),(a,b)->a,LinkedHashMap::new));for(List<Camper> component:components){List<Camper> remaining=new ArrayList<>(component);while(!remaining.isEmpty()){Room best=available.stream().filter(r->placed.get(r.getId()).size()<r.getCapacity()).max(Comparator.comparingDouble((Room r)->scoreChunk(remaining,placed.get(r.getId()),r.getCapacity()-placed.get(r.getId()).size(),camp.getStartDate())).thenComparing(Room::getName,Comparator.reverseOrder())).orElseThrow();int take=Math.min(remaining.size(),best.getCapacity()-placed.get(best.getId()).size());List<Camper> chunk=new ArrayList<>(remaining.subList(0,take));placed.get(best.getId()).addAll(chunk);remaining.subList(0,take).clear();}}placed.forEach((id,list)->{Room r=rooms.findById(id).orElseThrow();list.forEach(c->c.setRoom(r));});}}
 @Transactional public void assignGroups(UUID campId,GroupRequest req){var camp=camps.findById(campId).orElseThrow();List<Camper> all=campers.findByCampIdOrderByName(campId);if(all.isEmpty())throw new IllegalStateException("Import campers first");int count=req.numberOfGroups()!=null?req.numberOfGroups():(int)Math.ceil((double)all.size()/req.membersPerGroup());if(count<1)throw new IllegalArgumentException("At least one group is required");groups.deleteByCampId(campId);List<DiscussionGroup> gs=new ArrayList<>();for(int i=1;i<=count;i++){DiscussionGroup g=new DiscussionGroup();g.setCamp(camp);g.setName("Group "+i);g.setCapacity((int)Math.ceil((double)all.size()/count));g.setGenderSeparated(req.genderSeparated());gs.add(groups.save(g));}List<Camper> ordered=new ArrayList<>(all);ordered.sort(Comparator.comparingInt((Camper c)->c.ageOn(camp.getStartDate())).thenComparing(Camper::getName));for(int i=0;i<ordered.size();i++){int cycle=i%(count*2);int index=cycle<count?cycle:(count*2-1-cycle);ordered.get(i).setDiscussionGroup(gs.get(index));}}
 private double scoreChunk(List<Camper> source,List<Camper> room,int space,java.time.LocalDate date){List<Camper>x=source.subList(0,Math.min(space,source.size()));double age=room.isEmpty()?0:-Math.abs(x.stream().mapToInt(c->c.ageOn(date)).average().orElse(0)-room.stream().mapToInt(c->c.ageOn(date)).average().orElse(0));return x.size()*100+age;}
 private Map<UUID,Set<UUID>> friendMap(UUID id){Map<UUID,Set<UUID>>m=new HashMap<>();for(Preference p:preferences.findByCamperCampId(id))if(p.getMatchedCamper()!=null){m.computeIfAbsent(p.getCamper().getId(),x->new HashSet<>()).add(p.getMatchedCamper().getId());m.computeIfAbsent(p.getMatchedCamper().getId(),x->new HashSet<>()).add(p.getCamper().getId());}return m;}
 private List<List<Camper>> components(List<Camper> people,Map<UUID,Set<UUID>> f){Map<UUID,Camper>map=people.stream().collect(Collectors.toMap(Camper::getId,x->x));Set<UUID>seen=new HashSet<>();List<List<Camper>>out=new ArrayList<>();for(Camper start:people)if(seen.add(start.getId())){List<Camper>part=new ArrayList<>();Deque<UUID>q=new ArrayDeque<>();q.add(start.getId());while(!q.isEmpty()){UUID id=q.remove();part.add(map.get(id));for(UUID n:f.getOrDefault(id,Set.of()))if(map.containsKey(n)&&seen.add(n))q.add(n);}part.sort(Comparator.comparing(Camper::getName));out.add(part);}return out;}
}
