package com.campkin.service;
import com.campkin.api.ApiModels.*; import com.campkin.config.AuthTokens; import com.campkin.domain.*; import com.campkin.repo.*; import jakarta.persistence.EntityNotFoundException; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.security.*; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;
@Service @RequiredArgsConstructor @Transactional public class AuthService {
 private final AppUserRepository users; private final UserSessionRepository sessions; private final CampRepository camps; private final CampMembershipRepository memberships; private final PasswordEncoder passwords; private final AuthContext auth; private final SecureRandom random=new SecureRandom();
 public AuthResponse register(RegisterRequest request){String email=request.email().trim().toLowerCase(Locale.ROOT);if(users.findByEmailIgnoreCase(email).isPresent())throw new IllegalArgumentException("An account already uses this email");boolean first=users.count()==0;AppUser user=new AppUser();user.setName(request.name().trim());user.setEmail(email);user.setPasswordHash(passwords.encode(request.password()));users.save(user);if(first)for(Camp camp:camps.findAll())addMembership(camp,user,CampMembership.Role.OWNER);return session(user);}
 public AuthResponse login(LoginRequest request){AppUser user=users.findByEmailIgnoreCase(request.email().trim()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Incorrect email or password"));if(!passwords.matches(request.password(),user.getPasswordHash()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Incorrect email or password");return session(user);}
 @Transactional(readOnly=true) public UserView me(){return view(auth.user());}
 public void logout(String token){if(token!=null&&!token.isBlank())sessions.deleteByTokenHash(AuthTokens.hash(token));}
 public Camp join(JoinCampRequest request){Camp camp=camps.findByJoinCodeIgnoreCase(request.code().trim()).orElseThrow(()->new EntityNotFoundException("No camp uses that join code"));AppUser user=auth.user();if(!memberships.existsByCampIdAndUserId(camp.getId(),user.getId()))addMembership(camp,user,CampMembership.Role.MEMBER);return camp;}
 private AuthResponse session(AppUser user){byte[] bytes=new byte[32];random.nextBytes(bytes);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);UserSession session=new UserSession();session.setUser(user);session.setTokenHash(AuthTokens.hash(token));session.setExpiresAt(Instant.now().plus(30,ChronoUnit.DAYS));sessions.save(session);return new AuthResponse(token,view(user));}
 private UserView view(AppUser user){return new UserView(user.getId(),user.getName(),user.getEmail());}
 private void addMembership(Camp camp,AppUser user,CampMembership.Role role){CampMembership membership=new CampMembership();membership.setCamp(camp);membership.setUser(user);membership.setRole(role);memberships.save(membership);}
}
