package com.campkin.service;
import com.campkin.api.ApiModels.*; import com.campkin.domain.*; import com.campkin.repo.*; import jakarta.persistence.EntityNotFoundException; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.*;
@Service @RequiredArgsConstructor @Transactional public class CampService {
 private final CampRepository camps; private final RoomRepository rooms; private final DiscussionGroupRepository groups; private final CaringGroupRepository caringGroups; private final LeaderRepository leaders; private final CamperRepository campers; private final PreferenceRepository preferences; private final RoomLeaderRepository roomLeaders; private final GroupLeaderRepository groupLeaders; private final CampMembershipRepository memberships; private final AuthContext auth;
 public List<Camp> list(){ return memberships.findByUserIdOrderByCampName(auth.user().getId()).stream().map(CampMembership::getCamp).toList(); }
 public Camp create(CampRequest r){ if(r.endDate().isBefore(r.startDate())) throw new IllegalArgumentException("End date must be after start date"); Camp c=new Camp(); c.setName(r.name());c.setStartDate(r.startDate());c.setEndDate(r.endDate());c.setDescription(r.description());c.setJoinCode(joinCode());camps.save(c);CampMembership membership=new CampMembership();membership.setCamp(c);membership.setUser(auth.user());membership.setRole(CampMembership.Role.OWNER);memberships.save(membership);return c; }
 public void deleteCamp(UUID campId){Camp c=camp(campId);camps.delete(c);}
 public Leader addLeader(UUID campId,LeaderRequest r){String normalized=NameMatcher.normalize(r.name());if(leaders.findByCampIdAndNormalizedName(campId,normalized).isPresent())throw new IllegalArgumentException("A leader with this name already exists");Leader x=new Leader();x.setCamp(camp(campId));x.setName(r.name().trim());x.setNormalizedName(normalized);x.setGender(r.gender());return leaders.save(x);}
 public Leader updateLeader(UUID id,LeaderRequest r){Leader x=leaders.findById(id).orElseThrow();String old=x.getName();String normalized=NameMatcher.normalize(r.name());leaders.findByCampIdAndNormalizedName(x.getCamp().getId(),normalized).filter(other->!other.getId().equals(id)).ifPresent(other->{throw new IllegalArgumentException("A leader with this name already exists");});if(r.gender()!=x.getGender()){boolean incompatibleRoom=roomLeaders.findByManagedRoomCampId(x.getCamp().getId()).stream().anyMatch(link->link.getName().equalsIgnoreCase(old)&&link.getManagedRoom().getGender()!=r.gender());boolean incompatibleCaring=caringGroups.findByCampIdOrderByName(x.getCamp().getId()).stream().anyMatch(group->group.getLeaderName().equalsIgnoreCase(old)&&group.getGender()!=r.gender());if(incompatibleRoom||incompatibleCaring)throw new IllegalStateException("Remove this leader from gender-specific Room and Caring assignments before changing gender");}x.setName(r.name().trim());x.setNormalizedName(normalized);x.setGender(r.gender());roomLeaders.findByManagedRoomCampId(x.getCamp().getId()).stream().filter(link->link.getName().equalsIgnoreCase(old)).forEach(link->link.setName(x.getName()));groupLeaders.findByGroupCampId(x.getCamp().getId()).stream().filter(link->link.getName().equalsIgnoreCase(old)).forEach(link->link.setName(x.getName()));caringGroups.findByCampIdOrderByName(x.getCamp().getId()).stream().filter(group->group.getLeaderName().equalsIgnoreCase(old)).forEach(group->group.setLeaderName(x.getName()));return x;}
 public void deleteLeader(UUID id){Leader x=leaders.findById(id).orElseThrow();UUID campId=x.getCamp().getId();boolean used=roomLeaders.findByManagedRoomCampId(campId).stream().anyMatch(link->link.getName().equalsIgnoreCase(x.getName()))||groupLeaders.findByGroupCampId(campId).stream().anyMatch(link->link.getName().equalsIgnoreCase(x.getName()))||caringGroups.findByCampIdOrderByName(campId).stream().anyMatch(group->group.getLeaderName().equalsIgnoreCase(x.getName()));if(used)throw new IllegalStateException("This leader is currently assigned. Remove the leader from Rooms, Discussion Groups, and Caring first.");leaders.delete(x);}
 public Room addRoom(UUID campId,RoomRequest r){ Room x=new Room();x.setCamp(camp(campId));x.setName(r.name());x.setCapacity(r.capacity());x.setGender(r.gender());return rooms.save(x); }
 public List<Room> addRooms(UUID campId,BatchRoomRequest r){Camp c=camp(campId);List<Room> existing=rooms.findByCampIdOrderByName(campId);Set<String> names=existing.stream().map(x->x.getName().toLowerCase(Locale.ROOT)).collect(Collectors.toSet());List<Room> created=new ArrayList<>();int number=1;while(created.size()<r.count()){String name="Room "+number++;if(names.add(name.toLowerCase(Locale.ROOT))){Room room=new Room();room.setCamp(c);room.setName(name);room.setCapacity(r.capacity());room.setGender(r.gender());created.add(rooms.save(room));}}return created;}
 public Room renameRoom(UUID roomId,RoomRenameRequest r){Room room=rooms.findById(roomId).orElseThrow(()->new EntityNotFoundException("Room not found"));String name=r.name().trim();boolean duplicate=rooms.findByCampIdOrderByName(room.getCamp().getId()).stream().anyMatch(x->!x.getId().equals(roomId)&&x.getName().equalsIgnoreCase(name));if(duplicate)throw new IllegalArgumentException("Another room already uses that name");room.setName(name);return room;}
 public void updateRoomLeaders(UUID roomId,RoomLeadersUpdateRequest request){Room managed=rooms.findById(roomId).orElseThrow(()->new EntityNotFoundException("Room not found"));List<RoomLeader> existing=roomLeaders.findByManagedRoomCampId(managed.getCamp().getId());Map<UUID,Long> otherBeds=existing.stream().filter(l->!l.getManagedRoom().getId().equals(roomId)).collect(Collectors.groupingBy(l->l.getSleepRoom().getId(),Collectors.counting()));Map<UUID,Long> proposed=request.leaders().stream().collect(Collectors.groupingBy(RoomLeaderItem::sleepRoomId,Collectors.counting()));for(var entry:proposed.entrySet()){Room sleep=rooms.findById(entry.getKey()).orElseThrow(()->new EntityNotFoundException("Sleeping room not found"));if(!sleep.getCamp().getId().equals(managed.getCamp().getId()))throw new IllegalArgumentException("Sleeping room belongs to another camp");if(sleep.getGender()!=managed.getGender())throw new IllegalArgumentException("Leader sleeping rooms must have the same gender");long occupied=campers.countByRoomId(sleep.getId())+otherBeds.getOrDefault(sleep.getId(),0L)+entry.getValue();if(occupied>sleep.getCapacity())throw new IllegalArgumentException(sleep.getName()+" does not have enough beds for these leaders");}roomLeaders.deleteByManagedRoomId(roomId);for(RoomLeaderItem item:request.leaders()){Leader selected=leader(item.leaderId(),managed.getCamp().getId());if(selected.getGender()!=managed.getGender())throw new IllegalArgumentException("Room leader gender must match the room");RoomLeader link=new RoomLeader();link.setManagedRoom(managed);link.setName(selected.getName());link.setSleepRoom(rooms.findById(item.sleepRoomId()).orElseThrow());roomLeaders.save(link);}managed.setLeaderName(null);managed.setLeaderSleepRoom(null);}
 public void updateGroupLeaders(UUID groupId,GroupLeadersUpdateRequest request){DiscussionGroup group=groups.findById(groupId).orElseThrow(()->new EntityNotFoundException("Group not found"));groupLeaders.deleteByGroupId(groupId);for(UUID leaderId:request.leaderIds()){Leader selected=leader(leaderId,group.getCamp().getId());GroupLeader link=new GroupLeader();link.setGroup(group);link.setName(selected.getName());groupLeaders.save(link);}}
 public void updateCaringLeader(UUID groupId,CaringLeaderUpdateRequest request){CaringGroup group=caringGroups.findById(groupId).orElseThrow(()->new EntityNotFoundException("Caring group not found"));Leader selected=leader(request.leaderId(),group.getCamp().getId());if(selected.getGender()!=group.getGender())throw new IllegalArgumentException("Caring leader gender must match the group");group.setLeaderName(selected.getName());}
 public void deleteRoom(UUID roomId){Room room=rooms.findById(roomId).orElseThrow(()->new EntityNotFoundException("Room not found"));campers.findByCampIdOrderByName(room.getCamp().getId()).stream().filter(c->c.getRoom()!=null&&c.getRoom().getId().equals(roomId)).forEach(c->c.setRoom(null));rooms.delete(room);}
 public void deleteCamper(UUID camperId){deleteCampers(List.of(camperId));}
 public void deleteCampers(List<UUID> camperIds){Set<UUID> removedIds=new HashSet<>(camperIds);List<Camper> removed=campers.findAllById(removedIds);if(removed.size()!=removedIds.size())throw new EntityNotFoundException("One or more campers were not found");Set<UUID> campIds=removed.stream().map(camper->camper.getCamp().getId()).collect(Collectors.toSet());for(UUID campId:campIds)for(Preference preference:preferences.findByCamperCampId(campId)){if(removedIds.contains(preference.getCamper().getId()))continue;if(preference.getMatchedCamper()!=null&&removedIds.contains(preference.getMatchedCamper().getId())){preference.setMatchedCamper(null);preference.setStatus(Domain.PreferenceStatus.UNRESOLVED);preference.setSimilarity(null);}if(preference.getAlternatives()!=null&&!preference.getAlternatives().isBlank()){String remaining=Arrays.stream(preference.getAlternatives().split(",")).filter(id->!removedIds.contains(UUID.fromString(id))).collect(Collectors.joining(","));preference.setAlternatives(remaining.isBlank()?null:remaining);if(remaining.isBlank()&&preference.getStatus()==Domain.PreferenceStatus.AMBIGUOUS)preference.setStatus(Domain.PreferenceStatus.UNRESOLVED);}}removedIds.forEach(preferences::deleteByCamperId);campers.deleteAll(removed);}
 public Camper saveCamper(UUID campId,String name,Domain.Gender gender,LocalDate birthdate){ Camper c=new Camper();c.setCamp(camp(campId));c.setName(name.trim());c.setNormalizedName(NameMatcher.normalize(name));c.setGender(gender);c.setBirthdate(birthdate);return campers.save(c); }
 public void move(UUID camperId,MoveRequest r){ Camper c=camper(camperId); if(r.roomId()!=null){Room room=rooms.findById(r.roomId()).orElseThrow();if(!room.getCamp().getId().equals(c.getCamp().getId()))throw new IllegalArgumentException("Room belongs to another camp");if(room.getGender()!=c.getGender())throw new IllegalArgumentException("Camper gender does not match room"); long used=campers.countByRoomId(room.getId())+roomLeaders.countBySleepRoomId(room.getId());if(c.getRoom()!=null&&c.getRoom().getId().equals(room.getId()))used--;if(used>=room.getCapacity())throw new IllegalArgumentException("Room capacity exceeded");c.setRoom(room);} if(r.groupId()!=null){DiscussionGroup group=groups.findById(r.groupId()).orElseThrow();if(!group.getCamp().getId().equals(c.getCamp().getId()))throw new IllegalArgumentException("Discussion group belongs to another camp");c.setDiscussionGroup(group);} if(r.caringGroupId()!=null){CaringGroup group=caringGroups.findById(r.caringGroupId()).orElseThrow();if(!group.getCamp().getId().equals(c.getCamp().getId()))throw new IllegalArgumentException("Caring group belongs to another camp");if(group.getGender()!=c.getGender())throw new IllegalArgumentException("Camper gender does not match the Caring group");c.setCaringGroup(group);} }
 public void updateGender(UUID camperId,GenderRequest r){if(r.gender()==Domain.Gender.UNKNOWN)throw new IllegalArgumentException("Choose Male or Female");Camper c=camper(camperId);c.setGender(r.gender());c.setGenderAssumed(false);c.setRoom(null);c.setCaringGroup(null);}
 public List<CamperView> search(UUID campId,String q){ return campers.findByCampIdAndNormalizedNameContainingIgnoreCaseOrderByName(campId,NameMatcher.normalize(q)).stream().map(this::view).toList(); }
 @Transactional(readOnly=true) public Dashboard dashboard(UUID campId){ Camp camp=camp(campId); List<Camper> cs=campers.findByCampIdOrderByName(campId);List<Room> campRooms=rooms.findByCampIdOrderByName(campId); List<RoomView> rs=campRooms.stream().map(r->roomView(r,cs,campRooms)).toList(); List<GroupView> gs=groups.findByCampIdOrderByName(campId).stream().map(g->groupView(g,cs)).toList();List<CaringGroupView> caring=caringGroups.findByCampIdOrderByName(campId).stream().map(g->caringGroupView(g,cs)).toList(); long boys=cs.stream().filter(c->c.getGender()==Domain.Gender.MALE).count();long girls=cs.stream().filter(c->c.getGender()==Domain.Gender.FEMALE).count();long unknown=cs.size()-boys-girls;long assumed=cs.stream().filter(Camper::isGenderAssumed).count(); long matched=preferences.countByCamperCampIdAndStatus(campId,Domain.PreferenceStatus.MATCHED); long amb=preferences.countByCamperCampIdAndStatus(campId,Domain.PreferenceStatus.AMBIGUOUS); long unr=preferences.countByCamperCampIdAndStatus(campId,Domain.PreferenceStatus.UNRESOLVED); double avg=cs.stream().mapToInt(c->c.ageOn(camp.getStartDate())).average().orElse(0); double sat=matched+amb+unr==0?100:100d*fulfilled(campId)/(matched+amb+unr); double spread=rs.stream().filter(r->r.occupancy()>0).mapToDouble(r->ageSpread(r.campers())).average().orElse(0); return new Dashboard(camp,rs,gs,caring,leaders.findByCampIdOrderByName(campId).stream().map(this::leaderView).toList(),cs.stream().map(this::view).toList(),new Stats(cs.size(),boys,girls,unknown,assumed,round(avg),matched,amb,unr,round(sat),round(spread))); }
 private long fulfilled(UUID id){return preferences.findByCamperCampId(id).stream().filter(p->p.getStatus()==Domain.PreferenceStatus.MATCHED&&p.getCamper().getRoom()!=null&&p.getMatchedCamper()!=null&&Objects.equals(p.getCamper().getRoom().getId(),p.getMatchedCamper().getRoom()==null?null:p.getMatchedCamper().getRoom().getId())).count();}
 private RoomView roomView(Room r,List<Camper> all,List<Room> campRooms){List<CamperView>x=all.stream().filter(c->c.getRoom()!=null&&c.getRoom().getId().equals(r.getId())).map(this::view).toList();List<LeaderView> leaders=roomLeaders.findByManagedRoomIdOrderByName(r.getId()).stream().map(l->new LeaderView(l.getId(),leaderId(r.getCamp().getId(),l.getName()),l.getName(),l.getSleepRoom().getId(),l.getSleepRoom().getName())).toList();long occupied=x.size()+roomLeaders.countBySleepRoomId(r.getId());return new RoomView(r.getId(),r.getName(),r.getCapacity(),r.getGender(),leaders,occupied,round(x.stream().mapToInt(CamperView::age).average().orElse(0)),x);}
 private GroupView groupView(DiscussionGroup g,List<Camper> all){List<CamperView>x=all.stream().filter(c->c.getDiscussionGroup()!=null&&c.getDiscussionGroup().getId().equals(g.getId())).map(this::view).toList();List<String> leaders=groupLeaders.findByGroupIdOrderByName(g.getId()).stream().map(GroupLeader::getName).toList();return new GroupView(g.getId(),g.getName(),g.getCapacity(),leaders,x.size(),round(x.stream().mapToInt(CamperView::age).average().orElse(0)),x);}
 private CaringGroupView caringGroupView(CaringGroup g,List<Camper> all){List<CamperView>x=all.stream().filter(c->c.getCaringGroup()!=null&&c.getCaringGroup().getId().equals(g.getId())).map(this::view).toList();return new CaringGroupView(g.getId(),g.getName(),leaderId(g.getCamp().getId(),g.getLeaderName()),g.getLeaderName(),g.getGender(),x.size(),round(x.stream().mapToInt(CamperView::age).average().orElse(0)),x);}
 public CamperView view(Camper c){List<PreferenceView> ps=preferences.findByCamperId(c.getId()).stream().map(p->new PreferenceView(p.getId(),p.getRawName(),p.getMatchedCamper()==null?null:p.getMatchedCamper().getName(),p.getStatus().name(),p.getSimilarity(),parseIds(p.getAlternatives()))).toList();return new CamperView(c.getId(),c.getName(),c.getGender(),c.isGenderAssumed(),c.getBirthdate(),c.ageOn(c.getCamp().getStartDate()),c.getRoom()==null?null:c.getRoom().getId(),c.getRoom()==null?null:c.getRoom().getName(),c.getDiscussionGroup()==null?null:c.getDiscussionGroup().getId(),c.getDiscussionGroup()==null?null:c.getDiscussionGroup().getName(),c.getCaringGroup()==null?null:c.getCaringGroup().getId(),c.getCaringGroup()==null?null:c.getCaringGroup().getName(),ps);}
 private List<UUID> parseIds(String s){if(s==null||s.isBlank())return List.of();return Arrays.stream(s.split(",")).map(UUID::fromString).toList();} private double ageSpread(List<CamperView>x){if(x.isEmpty())return 0;IntSummaryStatistics s=x.stream().mapToInt(CamperView::age).summaryStatistics();return s.getMax()-s.getMin();} private double round(double x){return Math.round(x*10)/10d;} private Camp camp(UUID id){return camps.findById(id).orElseThrow(()->new EntityNotFoundException("Camp not found"));} private Camper camper(UUID id){return campers.findById(id).orElseThrow(()->new EntityNotFoundException("Camper not found"));}
 private String joinCode(){String code;do{code=UUID.randomUUID().toString().replace("-","").substring(0,8).toUpperCase(Locale.ROOT);}while(camps.existsByJoinCodeIgnoreCase(code));return code;}
 private Leader leader(UUID id,UUID campId){Leader leader=leaders.findById(id).orElseThrow(()->new EntityNotFoundException("Leader not found"));if(!leader.getCamp().getId().equals(campId))throw new IllegalArgumentException("Leader belongs to another camp");return leader;}
 private UUID leaderId(UUID campId,String name){return leaders.findByCampIdAndNormalizedName(campId,NameMatcher.normalize(name)).map(Leader::getId).orElse(null);}
 private LeaderRecordView leaderView(Leader leader){return new LeaderRecordView(leader.getId(),leader.getName(),leader.getGender());}
}
