package com.campkin.service;
import com.campkin.api.ApiModels.*; import com.campkin.domain.*; import com.campkin.repo.*; import jakarta.persistence.EntityNotFoundException; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.*;
@Service @RequiredArgsConstructor @Transactional public class CampService {
 private final CampRepository camps; private final RoomRepository rooms; private final DiscussionGroupRepository groups; private final CamperRepository campers; private final PreferenceRepository preferences;
 public List<Camp> list(){ return camps.findAll(); }
 public Camp create(CampRequest r){ if(r.endDate().isBefore(r.startDate())) throw new IllegalArgumentException("End date must be after start date"); Camp c=new Camp(); c.setName(r.name());c.setStartDate(r.startDate());c.setEndDate(r.endDate());c.setDescription(r.description());return camps.save(c); }
 public Room addRoom(UUID campId,RoomRequest r){ Room x=new Room();x.setCamp(camp(campId));x.setName(r.name());x.setCapacity(r.capacity());x.setGender(r.gender());return rooms.save(x); }
 public List<Room> addRooms(UUID campId,BatchRoomRequest r){Camp c=camp(campId);List<Room> existing=rooms.findByCampIdOrderByName(campId);Set<String> names=existing.stream().map(x->x.getName().toLowerCase(Locale.ROOT)).collect(Collectors.toSet());List<Room> created=new ArrayList<>();int number=1;while(created.size()<r.count()){String name="Room "+number++;if(names.add(name.toLowerCase(Locale.ROOT))){Room room=new Room();room.setCamp(c);room.setName(name);room.setCapacity(r.capacity());room.setGender(r.gender());created.add(rooms.save(room));}}return created;}
 public Room renameRoom(UUID roomId,RoomRenameRequest r){Room room=rooms.findById(roomId).orElseThrow(()->new EntityNotFoundException("Room not found"));String name=r.name().trim();boolean duplicate=rooms.findByCampIdOrderByName(room.getCamp().getId()).stream().anyMatch(x->!x.getId().equals(roomId)&&x.getName().equalsIgnoreCase(name));if(duplicate)throw new IllegalArgumentException("Another room already uses that name");room.setName(name);return room;}
 public Camper saveCamper(UUID campId,String name,Domain.Gender gender,LocalDate birthdate){ Camper c=new Camper();c.setCamp(camp(campId));c.setName(name.trim());c.setNormalizedName(NameMatcher.normalize(name));c.setGender(gender);c.setBirthdate(birthdate);return campers.save(c); }
 public void move(UUID camperId,MoveRequest r){ Camper c=camper(camperId); if(r.roomId()!=null){Room room=rooms.findById(r.roomId()).orElseThrow(); if(room.getGender()!=c.getGender())throw new IllegalArgumentException("Camper gender does not match room"); long used=campers.countByRoomId(room.getId())+(room.getLeaderName()==null?0:1);if(used>=room.getCapacity())throw new IllegalArgumentException("Room capacity exceeded");c.setRoom(room);} if(r.groupId()!=null)c.setDiscussionGroup(groups.findById(r.groupId()).orElseThrow()); }
 public void updateGender(UUID camperId,GenderRequest r){if(r.gender()==Domain.Gender.UNKNOWN)throw new IllegalArgumentException("Choose Male or Female");Camper c=camper(camperId);c.setGender(r.gender());c.setRoom(null);}
 public List<CamperView> search(UUID campId,String q){ return campers.findByCampIdAndNormalizedNameContainingIgnoreCaseOrderByName(campId,NameMatcher.normalize(q)).stream().map(this::view).toList(); }
 @Transactional(readOnly=true) public Dashboard dashboard(UUID campId){ Camp camp=camp(campId); List<Camper> cs=campers.findByCampIdOrderByName(campId); List<RoomView> rs=rooms.findByCampIdOrderByName(campId).stream().map(r->roomView(r,cs)).toList(); List<GroupView> gs=groups.findByCampIdOrderByName(campId).stream().map(g->groupView(g,cs)).toList(); long boys=cs.stream().filter(c->c.getGender()==Domain.Gender.MALE).count();long girls=cs.stream().filter(c->c.getGender()==Domain.Gender.FEMALE).count();long unknown=cs.size()-boys-girls; long matched=preferences.countByCamperCampIdAndStatus(campId,Domain.PreferenceStatus.MATCHED); long amb=preferences.countByCamperCampIdAndStatus(campId,Domain.PreferenceStatus.AMBIGUOUS); long unr=preferences.countByCamperCampIdAndStatus(campId,Domain.PreferenceStatus.UNRESOLVED); double avg=cs.stream().mapToInt(c->c.ageOn(camp.getStartDate())).average().orElse(0); double sat=matched+amb+unr==0?100:100d*fulfilled(campId)/(matched+amb+unr); double spread=rs.stream().filter(r->r.occupancy()>0).mapToDouble(r->ageSpread(r.campers())).average().orElse(0); return new Dashboard(camp,rs,gs,cs.stream().map(this::view).toList(),new Stats(cs.size(),boys,girls,unknown,round(avg),matched,amb,unr,round(sat),round(spread))); }
 private long fulfilled(UUID id){return preferences.findByCamperCampId(id).stream().filter(p->p.getStatus()==Domain.PreferenceStatus.MATCHED&&p.getCamper().getRoom()!=null&&p.getMatchedCamper()!=null&&Objects.equals(p.getCamper().getRoom().getId(),p.getMatchedCamper().getRoom()==null?null:p.getMatchedCamper().getRoom().getId())).count();}
 private RoomView roomView(Room r,List<Camper> all){List<CamperView>x=all.stream().filter(c->c.getRoom()!=null&&c.getRoom().getId().equals(r.getId())).map(this::view).toList();long occupied=x.size()+(r.getLeaderName()==null?0:1);return new RoomView(r.getId(),r.getName(),r.getCapacity(),r.getGender(),r.getLeaderName(),occupied,round(x.stream().mapToInt(CamperView::age).average().orElse(0)),x);}
 private GroupView groupView(DiscussionGroup g,List<Camper> all){List<CamperView>x=all.stream().filter(c->c.getDiscussionGroup()!=null&&c.getDiscussionGroup().getId().equals(g.getId())).map(this::view).toList();return new GroupView(g.getId(),g.getName(),g.getCapacity(),x.size(),round(x.stream().mapToInt(CamperView::age).average().orElse(0)),x);}
 public CamperView view(Camper c){List<PreferenceView> ps=preferences.findByCamperId(c.getId()).stream().map(p->new PreferenceView(p.getId(),p.getRawName(),p.getMatchedCamper()==null?null:p.getMatchedCamper().getName(),p.getStatus().name(),p.getSimilarity(),parseIds(p.getAlternatives()))).toList();return new CamperView(c.getId(),c.getName(),c.getGender(),c.getBirthdate(),c.ageOn(c.getCamp().getStartDate()),c.getRoom()==null?null:c.getRoom().getId(),c.getRoom()==null?null:c.getRoom().getName(),c.getDiscussionGroup()==null?null:c.getDiscussionGroup().getId(),c.getDiscussionGroup()==null?null:c.getDiscussionGroup().getName(),ps);}
 private List<UUID> parseIds(String s){if(s==null||s.isBlank())return List.of();return Arrays.stream(s.split(",")).map(UUID::fromString).toList();} private double ageSpread(List<CamperView>x){if(x.isEmpty())return 0;IntSummaryStatistics s=x.stream().mapToInt(CamperView::age).summaryStatistics();return s.getMax()-s.getMin();} private double round(double x){return Math.round(x*10)/10d;} private Camp camp(UUID id){return camps.findById(id).orElseThrow(()->new EntityNotFoundException("Camp not found"));} private Camper camper(UUID id){return campers.findById(id).orElseThrow(()->new EntityNotFoundException("Camper not found"));}
}
