package com.campkin.service;
import com.campkin.domain.*; import com.campkin.repo.*; import lombok.RequiredArgsConstructor; import org.apache.commons.text.similarity.LevenshteinDistance; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.text.Normalizer; import java.util.*;
@Service @RequiredArgsConstructor public class NameMatcher {
 private final CamperRepository campers; private final PreferenceRepository preferences; @Value("${app.fuzzy-threshold:0.85}") double threshold;
 public static String normalize(String s){return Normalizer.normalize(s,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9 ]"," ").replaceAll("\\s+"," ").trim();}
 public static List<String> split(String raw){return raw==null?List.of():Arrays.stream(raw.split("[,;/\\-\\r\\n]+")).map(String::trim).filter(x->!x.isBlank()).toList();}
 @Transactional public void resolve(UUID campId){List<Camper> all=campers.findByCampIdOrderByName(campId);for(Preference p:preferences.findByCamperCampId(campId)){String n=normalize(p.getRawName());List<Scored> scores=all.stream().filter(c->!c.getId().equals(p.getCamper().getId())).map(c->new Scored(c,similarity(n,c.getNormalizedName()))).sorted(Comparator.comparingDouble(Scored::score).reversed().thenComparing(x->x.camper().getName())).toList();if(scores.isEmpty()||scores.getFirst().score()<threshold){p.setStatus(Domain.PreferenceStatus.UNRESOLVED);continue;}double best=scores.getFirst().score();List<Scored> tied=scores.stream().filter(x->best-x.score()<0.035).toList();p.setSimilarity(best);if(tied.size()>1){p.setStatus(Domain.PreferenceStatus.AMBIGUOUS);p.setAlternatives(tied.stream().map(x->x.camper().getId().toString()).collect(java.util.stream.Collectors.joining(",")));}else{p.setMatchedCamper(tied.getFirst().camper());p.setStatus(Domain.PreferenceStatus.MATCHED);p.setAlternatives(null);}}}
 public double similarity(String a,String b){int max=Math.max(a.length(),b.length());if(max==0)return 1;int d=LevenshteinDistance.getDefaultInstance().apply(a,b);double full=1d-(double)d/max;Set<String>as=new HashSet<>(Arrays.asList(a.split(" ")));Set<String>bs=new HashSet<>(Arrays.asList(b.split(" ")));as.retainAll(bs);double token=bs.isEmpty()?0:(double)as.size()/bs.size();return Math.max(full,token*.92);}
 record Scored(Camper camper,double score){}
}
