package com.campkin.api;
import com.campkin.api.ApiModels.*; import com.campkin.domain.*; import com.campkin.repo.*; import com.campkin.service.*; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api") @RequiredArgsConstructor public class CampController {
 private final CampService service; private final ExcelImportService importer; private final AssignmentService assignments; private final PdfService pdf; private final PreferenceRepository preferences; private final CamperRepository campers; private final AccessService access;
 @GetMapping("/health") Map<String,String> health(){return Map.of("status","ok");}
 @GetMapping("/camps") List<Camp> camps(){return service.list();} @PostMapping("/camps") @ResponseStatus(HttpStatus.CREATED) Camp create(@Valid @RequestBody CampRequest r){return service.create(r);}
 @DeleteMapping("/camps/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteCamp(@PathVariable UUID id){access.requireOwner(id);service.deleteCamp(id);}
 @GetMapping("/camps/{id}/dashboard") Dashboard dashboard(@PathVariable UUID id){access.requireCamp(id);return service.dashboard(id);} @GetMapping("/camps/{id}/campers/search") List<CamperView> search(@PathVariable UUID id,@RequestParam String q){access.requireCamp(id);return service.search(id,q);}
 @PostMapping("/camps/{id}/rooms") @ResponseStatus(HttpStatus.CREATED) Room room(@PathVariable UUID id,@Valid @RequestBody RoomRequest r){access.requireCamp(id);return service.addRoom(id,r);}
 @PostMapping("/camps/{id}/rooms/batch") @ResponseStatus(HttpStatus.CREATED) List<Room> rooms(@PathVariable UUID id,@Valid @RequestBody BatchRoomRequest r){access.requireCamp(id);return service.addRooms(id,r);}
 @PatchMapping("/rooms/{id}") Room renameRoom(@PathVariable UUID id,@Valid @RequestBody RoomRenameRequest r){access.requireRoom(id);return service.renameRoom(id,r);}
 @PutMapping("/rooms/{id}/leaders") void updateRoomLeaders(@PathVariable UUID id,@Valid @RequestBody RoomLeadersUpdateRequest r){access.requireRoom(id);service.updateRoomLeaders(id,r);}
 @PutMapping("/groups/{id}/leaders") void updateGroupLeaders(@PathVariable UUID id,@Valid @RequestBody GroupLeadersUpdateRequest r){access.requireGroup(id);service.updateGroupLeaders(id,r);}
 @DeleteMapping("/rooms/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteRoom(@PathVariable UUID id){access.requireRoom(id);service.deleteRoom(id);}
 @PostMapping(value="/camps/{id}/import",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ImportResult importCampers(@PathVariable UUID id,@RequestPart MultipartFile file)throws IOException{access.requireCamp(id);return importer.importFile(id,file);}
 @PostMapping("/camps/{id}/infer-genders") Map<String,Integer> inferGenders(@PathVariable UUID id){access.requireCamp(id);return Map.of("inferred",importer.inferGenders(id));}
 @PostMapping("/camps/{id}/assign/rooms") void assignRooms(@PathVariable UUID id,@Valid @RequestBody GenerateRoomsRequest r){access.requireCamp(id);assignments.assignRooms(id,r);} @PostMapping("/camps/{id}/assign/groups") void assignGroups(@PathVariable UUID id,@Valid @RequestBody GroupRequest r){access.requireCamp(id);assignments.assignGroups(id,r);}
 @PatchMapping("/campers/{id}/assignment") void move(@PathVariable UUID id,@RequestBody MoveRequest r){access.requireCamper(id);service.move(id,r);}
 @PatchMapping("/campers/{id}/gender") void gender(@PathVariable UUID id,@Valid @RequestBody GenderRequest r){access.requireCamper(id);service.updateGender(id,r);}
 @DeleteMapping("/campers/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteCamper(@PathVariable UUID id){access.requireCamper(id);service.deleteCamper(id);}
 @DeleteMapping("/campers") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteCampers(@Valid @RequestBody CamperIdsRequest request){request.camperIds().forEach(access::requireCamper);service.deleteCampers(request.camperIds());}
 @PatchMapping("/preferences/{id}/resolve") void resolve(@PathVariable UUID id,@Valid @RequestBody MatchRequest r){access.requirePreference(id);access.requireCamper(r.matchedCamperId());Preference p=preferences.findById(id).orElseThrow();Camper c=campers.findById(r.matchedCamperId()).orElseThrow();if(c.getCamp().getId().equals(p.getCamper().getCamp().getId())){p.setMatchedCamper(c);p.setStatus(Domain.PreferenceStatus.MATCHED);p.setSimilarity(1d);p.setAlternatives(null);}else throw new IllegalArgumentException("Camper belongs to another camp");}
 @GetMapping(value="/camps/{id}/exports/rooms.pdf",produces=MediaType.APPLICATION_PDF_VALUE) ResponseEntity<byte[]> roomPdf(@PathVariable UUID id){access.requireCamp(id);return download(pdf.rooms(id),"room-assignments.pdf");} @GetMapping(value="/camps/{id}/exports/groups.pdf",produces=MediaType.APPLICATION_PDF_VALUE) ResponseEntity<byte[]> groupPdf(@PathVariable UUID id){access.requireCamp(id);return download(pdf.groups(id),"discussion-groups.pdf");}
 private ResponseEntity<byte[]> download(byte[] bytes,String name){return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+name+"\"").body(bytes);}
}
